name = "QRMumps"
uuid = "422b30a1-cc69-4d85-abe7-cc07b540c444"
authors = ["Alfredo Buttari (@abuttari), Alexis Montoison (@amontoison)"]
version = "0.2.6"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
qr_mumps_jll = "e37b5aa0-c611-5f0f-83fb-aee446c0b77e"

[weakdeps]
SparseMatricesCOO = "fa32481b-f100-4b48-8dc8-c62f61b13870"

[extensions]
QRMumpsSparseMatricesCOOExt = "SparseMatricesCOO"

[compat]
Libdl = "1.10"
LinearAlgebra = "1.10"
OpenBLAS32_jll = "0.3.10"
Printf = "1.10"
Random = "1.10"
SparseArrays = "1.10"
SparseMatricesCOO = "0.2.2"
Test = "1.10"
julia = "1.10"
qr_mumps_jll = "3.1.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
